apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
